Add `/regions/stats` page
FixMyBerlin/atlas-app pull request #153
Opened 2024-10-28 15:48 UTC by rush42

Add a page [`/regions/stats`](https://staging.radverkehrsatlas.de/regionen/stats) to display our analysis.

2024-10-28 17:05 UTC, tordans requested changes
Ich habe das Gefühl, wir sollten erstmal keine Prisma types queries verwenden. 

Es ist gut, dass wir sie ausprobiert haben … aber sie bringen IMO zu viel zusätzliche Komplexität rein, für zu wenig Gewinn.

Es müsste doch genauso gut möglich sein, die Query direkt in getAllStat zu schreiben und dann getAllStat aus der API Route und aus der Page aufzurufen, richtig?
Das wäre dann das normale Blitz-Setup das wir auch sonst haben.

Wir sparen uns dann, dass wir dokumentieren und debuggen müssen, wie das mit den Types Queries und diesen eingecheckten node_modules Files funktioniert.

Und wir müssen nicht monitoren, was Prisma in dem Bereich so updatet…

2024-10-29 09:20 UTC, rush42 commented
Ok, dann mache ich es mit einer normalen raw query. IMO ist das feature sehr praktisch und wenn wir beim Build DB Zugriff hätten, dann würde es die Komplexität deutlich verringern, da kein Blitz layer mehr benötigt werden würde und wir so die types auch im build generieren könnten und nicht einchecken müssten.

2024-10-29 14:32 UTC, tordans requested changes
Sieht gut aus

2024-10-29 14:32 UTC, tordans commented on app.Dockerfile
> +COPY /app/node_modules/.prisma/client/sql /app/node_modules/.prisma/client/sql
```suggestion
```

2024-10-29 14:32 UTC, tordans commented on app/src/app/api/stats/route.ts
> +  }
```suggestion
  } catch (error) {
    console.error(error) // Log files
    return Response.json(
      {
        error: 'Internal Server Error',
        info: isProd ? undefined : error,
      },
      { status: 500 },
    )
  }
```

2024-10-29 14:32 UTC, tordans commented on app/src/app/api/stats/route.ts
> +import { NextResponse } from 'next/server'
```suggestion
import { NextResponse } from 'next/server'
import { isProd } from '@/src/app/_components/utils/isEnv'
```

2024-10-29 15:22 UTC, merged